### ISSUE TITLE
Add basic README

### ISSUE THREAD

**Issue by amercader** [ckan/ckan.org#1]
Add a README file with:

* Description of the repository
* Instructions for a local development install
* License (AGPL)
* BONUS: Instructions on how to deploy changes

**Comment by Alex-Pavlyuk** [comment]
the first version of the readme file was pushed, I contents the Local environment setup manual.
We still need to improve it to add all standard descriptions. It will be done a bit later

**Comment by Alex-Pavlyuk** [comment]
The Readme file was updated, also some requirements on how to install the site were updated as well. @amercader is it better now?

**Comment by amercader** [comment]
README looks great, thanks @Alex-Pavlyuk
