### ISSUE TITLE
"Speak with us" snippet is inconsistent across pages

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#10]
**Describe the bug**
On Community support page "Speak with us" snippet differs from the same snippet on Home page. How it differs: on Community support page "Speak with us" consists of email box (which we don't need) and a "Schedule a meeting" button.
![community-support-speak-with-us](https://user-images.githubusercontent.com/78435662/126635923-9ea28a66-04bd-4fb8-965b-c2d933b4a8c9.PNG)

**Expected behaviour**
All "Speak with us" snippets must be the same across all pages. The right one is the the one we have on Home page. Flow: When clicking on "Schedule a meeting", a contact form pops-up (no need of email box).
![image](https://user-images.githubusercontent.com/78435662/126634851-ffca4c60-8cbf-42d4-81bf-aa8f9ad8cfd7.png)

**Comment by Engerrs** [comment]
Hi @Alex-Pavlyuk , the first version is hided and on some place is replaced with the popup form. Will be deployed soon to PROD.

**Comment by Alex-Pavlyuk** [comment]
done
