### ISSUE TITLE
Blog posts show creation date, not publication one

### ISSUE THREAD

**Issue by amercader** [ckan/ckan.org#100]
For instance, the date of the last post about the security patch releases appears wrong, as I reused an earlier draft:

https://ckan.org/blog/get-latest-patch-releases-your-ckan-site-october-2022

https://ckan.org/admin/pages/307/edit/

It appears the UI shows the creation date, not the publication one.

**Comment by Alex-Pavlyuk** [comment]
@amercader yes, that's true, I will add it to the task queue but with low priority.

**Comment by popovayoana** [comment]
@Alex-Pavlyuk confirming that this has a lower priority compared to other issues such as #88

**Comment by Alex-Pavlyuk** [comment]
It was fixed already but wasn't deployed yet, will be fixes soon

**Comment by alexmorev** [comment]
@popovayoana , @Alex-Pavlyuk Fixed. Please check, test and give your feedback

**Comment by alexmorev** [comment]
@amercader The field "last published at" was used for post dates instead of "created" one as it was mentioned in this issue. Also verified all posts records in DB. And yes for some reasons there are many publishing dates repeating.

**Comment by Alex-Pavlyuk** [comment]
@amercader probably if it is superimportant we can migrate the dates from the old database...

**Comment by popovayoana** [comment]
@amercader i think we can close this as FIXED... (I'm unable to close it)
