### ISSUE TITLE
Add online chat 

### ISSUE THREAD

**Issue by thegostev** [ckan/ckan.org#106]
The task is to add the code of an online chat so incoming users can ask questions and engage with us.

When you're ready to add the code, please ping me, I'll get a subscription and will provide the code.

**Comment by alexmorev** [comment]
@thegostev Done. Online chat was added. Please check, test and give your feedback.

**Comment by Alex-Pavlyuk** [comment]
@thegostev have you registered the chat? because I don't see any dialog boxes

**Comment by thegostev** [comment]
All good. We ran out of trial, so for now the chat is not visible. It's tested, messages received, emails captured.
