### ISSUE TITLE
Add F.A.Q. v.1 (essential questions)

### ISSUE THREAD

**Issue by thegostev** [ckan/ckan.org#107]
Adding F.A.Q. will help decision makers and non-tech professionals understand implications of CKAN to their situation and how it can cover their needs.

The current version of F.A.Q. is minimalistic and goes by answering low amount of basic questions. Then we'd need to categorize questions with tags and provide search functionality.

**Preparation**
We should decide on the implementation. The simplest solution will work fine but we should have a possibility then to expand to up to 200 questions.

My proposition is to have either:
1. A list of questions on https://ckan.org/faq page where each question is a link to a page with the answer. So each answer has own page. 
2. Accordion list: each question is the line in the list, each answer rolls out when user clicks on the question.

**Implementation**
1. Create https://ckan.org/faq page.
3. Put it in the header menu between Events and Docs.
4. Add page to robots.txt (if it doesn't happen automatically).

**Content**
https://docs.google.com/document/d/1FrC8zVbsTK0QItNDoz8_O2Lbx2DDdnmNot4vVK25IcA/edit#heading=h.9epokvk2xipg

**Comment by Alex-Pavlyuk** [comment]
done
