### ISSUE TITLE
Filter blog posts by tag is not possible

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#11]
**Description**
We have tags for the blog posts but it is impossible to filter them by tag - tags are not clickable.

**Expected behaviour**
When clicking on a blog post tag, we want to be able to see all blog posts with this tag. Now this works only when you click on the author - it gives you all posts written by this author.

![tags](https://user-images.githubusercontent.com/78435662/127193168-852b8bd1-4228-4cfb-b521-d0a2f50773b8.png)

**Comment by Alex-Pavlyuk** [comment]
Hi @popovayoana it was deployed, pls check how it works now

**Comment by popovayoana** [comment]
FIXED.
