### ISSUE TITLE
Add a special editable field for blog post author 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#12]
**Description**
There's no special editable field for blog post author (in admin panel) which leads to: the moderator that publishes the article is marked as the author which might not be the case.

**Expected behaviour**
When posting a blog post, we want to have an editable field for author so that we can write the name of the real author.

**Comment by Engerrs** [comment]
Hi @Alex-Pavlyuk , enabled author field on Blog edit page. If the value is empty, it take the current user that is updating the Blog. If you specify a username, it will check if such User exists on CKAN.org and throw validation error if not.
Will be deployed soon to PROD.

**Comment by Alex-Pavlyuk** [comment]
I think we need to be able to enter just an author name and surname or use the current user name\surname if empty

**Comment by Alex-Pavlyuk** [comment]
found a bug after a recent deployment, we will fix it soon
