### ISSUE TITLE
Add "Sign up for our newsletter" form on website

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#121]
**Description**
We've launched a CKAN Monthly Newsletter and would like to invite people to stay connected by subscribing through an easy-to-use sign-up form on our website.

**Expected behaviour**
The newsletter form should be placed in prominent locations on the website, including the footer, blog page, on a dedicated subpage, e.g. ckan.org/newsletter and potentially as a pop-up. The form should consist of a minimal number of fields, such as a name and an email address. The form should be designed to be user-friendly and accessible, using clear and concise language, and ensuring that it can be used with keyboard-only navigation.

It's important to have a dedicated subpage, e.g. ckan.org/newsletter, where users can learn more about the newsletter and subscribe. Having such a subpage will help us share the newsletter on social media and invite them to subscribe. This subpage should include information about the frequency of the newsletter, the type of content it will contain, and the user's ability to opt-out at any time. Also link to Privacy Policy is a good practice but I am not sure of we have one... 

**Something to think about**
For an additional level of security and to prevent spam sign-ups, we might want to consider using a double opt-in process to confirm a user's subscription. This would involve sending a confirmation email to the user, containing a link that they must click to confirm their subscription. 

- Here's a prototype of the newsletter sign-up form: https://www.figma.com/proto/iDfXzrsgbDSuRxOLTc9CCa/CKAN-Monthly-Newsletter?node-id=4%3A23&scaling=min-zoom&page-id=0%3A1
- **Text: Ready to stay ahead of the curve? Join our CKAN Monthly Newsletter and get the inside scoop! From new developments to upcoming events and everything in between, you'll find it all here!** 

**Placement**
Ideally, we'd have several sign-up forms (see image references below)
1. In the footer
2. At the beginning of the Blog page
3. As a pop-up
4.  On a dedicated subpage ckan.org/newsletter

## Acceptance 
- [ ] "Sign up for our newsletter" form implemented on website
  - [ ] In the footer
  - [ ] At the beginning of the Blog page
  - [ ] As a pop-up
  - [ ] On a dedicated subpage ckan.org/newsletter
- [ ] Recaptcha or another anti-spam alternative is implemented
- [ ] Subscribers list is integrated with Mailchimp or another marketing tool

#### In the footer
Not sure - up to you. Probably right side is the only option.
![image](https://user-images.githubusercontent.com/78435662/216160701-13296865-30f8-4a60-b759-9a996a84ddd2.png)

How should it look like: It should be very simple, one line.
![image](https://user-images.githubusercontent.com/78435662/216160876-6545c8f8-f25a-416b-b41c-243c44412dcc.png)

#### At the beginning of the Blog page
![image](https://user-images.githubusercontent.com/78435662/216289428-4e50af1f-f090-4cc2-9983-ac1a115c097c.png)

#### As a pop-up
![image](https://user-images.githubusercontent.com/78435662/216163055-ebc9fcba-8061-4eb4-9eea-de9841f15599.png)

#### On a dedicated subpage ckan.org/newsletter
![image](https://user-images.githubusercontent.com/78435662/216287184-5f8dbc32-64c7-4bed-8614-9c76c65280aa.png)

See here: https://about.google/intl/ALL_us/email-newsletter-sign-up/

**Comment by popovayoana** [comment]
@alexmorev @Alex-Pavlyuk CKAN Monthly Newsletter #1 is already a fact so it'd be cool if we can implement a subscription form soon...

**Comment by thegostev** [comment]
Hey, @popovayoana! It's quite well detailed task. If I got it right - the idea is to use monthly newsletter as the most important email capture form for now, which makes sense to me. If it's so should we ditch "register for webinar form"?

Here are a few thoughts:
1. We'd need an email subscription form on the first screen. Writing to avoid potential conflict. It'll be similar looking email entry form where we ask people for email to be onboarded. Then we're sending onboarding series and eventually can send a newsletter. Thus the most important question is - **do we want to have one unified form or three separate forms for each occasion?**
2. It's a JS library for exit pop-ups, can't recall the name. I'm not sure if I'm for or against having the exit pop-up. Pros: lead capturing if we offer something that provides additional value. Cons: visible marketing tools contradict a bit with the non-profit engineering-led mentality.
3. I'm for writing what exactly user gets, like "Summary of most important happenings in CKAN world. Sent monthly. No spamming or commercials".
4. Should we have consent checkboxes if we'd like to use these emails aside of the newsletter? It brings us to the first point around the unified form.
5. I like the form on the blog page. What concerns me is that user should scroll to see blog posts. What do you think about adding the form between 1st and 2nd blog post?

**Comment by popovayoana** [comment]
@thegostev we want the webinar form as well so it should stay.

> 1. We'd need an email subscription form on the first screen. Writing to avoid potential conflict. It'll be similar looking email entry form where we ask people for email to be onboarded. Then we're sending onboarding series and eventually can send a newsletter. Thus the most important question is - do we want to have one unified form or three separate forms for each occasion?
We need a webinar form, contact form and newsletter form. I don't see how they can be merged.

> 4. I'm for writing what exactly user gets, like "Summary of most important happenings in CKAN world. Sent monthly. No spamming or commercials".
Sounds good, I like it - will change the mockup

> 5. Should we have consent checkboxes if we'd like to use these emails aside of the newsletter? It brings us to the first point around the unified form.

Consent checkboxes are not needed in the newsletter form. Again, unified form doesn't make sense to me - we do need to have a marketing consent on contact form but we cannot merge those stuff... 

> 7. I like the form on the blog page. What concerns me is that user should scroll to see blog posts. What do you think about adding the form between 1st and 2nd blog post? 

Sounds weird to me cause you break featured post and the other posts but if it looks good and make sense, I don't mind

**Comment by popovayoana** [comment]
@alexmorev @afantastic! 🥰 // cc @Alex-Pavlyuk @thegostev 

I can see we're progressing with this and we now have one in the footer and one in blog page
![image](https://user-images.githubusercontent.com/78435662/221815236-2db32b26-08d8-49ee-966e-8925e7bf65c9.png)

![image](https://user-images.githubusercontent.com/78435662/221815081-6b5d5e8e-82fc-4e91-b920-da34c0b9ede4.png)

I'm aware this is still _in progress_, just want to make sure we keep few things in mind
1. footer
I think we can have something like that below. The style of the button should keep the style of all buttons across website. And in order to avoid being overwhelmed by too many elements, I suggest we skip boxes and just leave lines (it's lighter and gives more space)
![Footer form](https://user-images.githubusercontent.com/78435662/221835828-ebffd371-f6d1-42eb-91d7-d987caf4c4b2.png)

3. blog form
I love it! It's nice and clean! I like the card style and the shadow effect. What I'd improve is:
3.1. same as above: let's keep button style + let's just have lines instead of boxes
3.2. let's fix the image as it looks cut: I've added [a new image here with longer rope](https://drive.google.com/drive/folders/1-VrCgY6M2kejmWbaoKdou-59Bw5VKwjT?usp=sharing), let me know if it works

note: the rope here doesn't look good but it's just for illustrative purposes - ideally it should look more natural as if it continues and be cut by the end of the newsletter card.  
![Blog form](https://user-images.githubusercontent.com/78435662/221835777-f38f9871-2868-4097-ba7d-42ca62e9f47f.png)

**Comment by alexmorev** [comment]
@popovayoana Done. Please check and give your feedback.
NOTE. 
1. The text of "Thanks messages" can be changed using admin: Contacts => Messages.
2. The dedicated Subscription page is on the following link [https://ckan.org/contacts/newsletter/subscription/](url)
3. This page is also suppose unsubscription possibility

**Comment by popovayoana** [comment]
@alexmorev everything looks perfect! thank you big time! just two questions:
 1. do we have the hidden recaptcha thing implemented? (otherwise we get a lot of spam)
 2. can we link the subscribers list with Mailchimp? (just like the webinar one is)
 
and one thing re the dedicated Subscription page:

1. the text alignment doesn't look very good atm
![image](https://user-images.githubusercontent.com/78435662/224005780-b64b43e1-19b9-417e-a7d0-05c9b8a5ab6f.png)

can we have it this way instead?
- delete most of the text and leave just name, email, subscribe
- instead of unsubscribe checkbox, let's just have: _"Sign up to receive news and updates from CKAN. Your information will be used in accordance with our privacy policy. You may opt out at any time."_

how it should look:
![Newsletter Snippet](https://user-images.githubusercontent.com/78435662/224016520-c3aed93e-f1b7-4f7f-953c-f94580b5b993.png)

2. and also, can we have it here? > https://ckan.org/newsletter/subscription/

thanks 🙏 
// cc @Alex-Pavlyuk

**Comment by popovayoana** [comment]
@alexmorev oh, just saw there's a typo: "Ready to **say** ahead of the curve? should be **stay**

**Comment by popovayoana** [comment]
@alexmorev forgot that there should be a final confirmation message that says the user is now subscribed... cc // @Alex-Pavlyuk

We are obviously doing a double opt-in process for our CKAN Monthly Newsletter subscription. This means that once users click on the confirmation link provided in the initial confirmation email, we should provide them with a final confirmation message to indicate that their subscription has been successfully confirmed. I see two potential options:

Option 1 - On-site Confirmation:
When users click the confirmation link in the initial email, they should be redirected to a dedicated page on ckan.org (or some pop-up) displaying the following message:

> Congratulations! 
> Your subscription to the CKAN.org newsletter has been successfully confirmed!

Option 2 - Final Confirmation Email:
Alternatively, once users click on the confirmation link, we can automatically send them a final confirmation email containing the message:

> Subject: You're All Set! Welcome to the CKAN Community 🎉
> 
> Hello,
> 
> Congratulations! Your subscription to the CKAN Monthly newsletter has been successfully confirmed! We're thrilled to have you as a part of our community and can't wait to share the latest news, articles, and updates about CKAN with you.
> 
> As a subscriber, you now have exclusive access to insightful articles, engaging stories, and important updates about CKAN. Be on the lookout for our next newsletter, and feel free to explore our website for more exciting content.
> 
> Thank you for joining the CKAN.org community, and we look forward to staying connected with you!
> 
> Warm regards,
> The CKAN Project Team

**Comment by alexmorev** [comment]
@popovayoana 
1. I'll try to solve the confirmation email issue on this week.
2. The issue about a final confirmation message I hope to do next.

**Comment by popovayoana** [comment]
@alexmorev hey alex, can we close this as fixed?

**Comment by alexmorev** [comment]
@popovayoana Of course. I've also added a subscription's confirmation message. Hope it will be deployed on prod asap.
