### ISSUE TITLE
URGENT FIX NEEDED: A bug with contact and webinar forms

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#130]
**Description**
There is some problem with the way subscription forms work - I don't know at what point it became messy but it is messy.
1. We don't receive the contact entries in Wagtail. We receive them in our emails but they are not recorded in Wagtail. (tested right now - I got an email but nothing in Wagtail)

2. We receive **the new webinar form** for both people that contact us and people that subscribe to the webinar.

**Expected behaviour**
1. We want all forms (contact, webinar, newsletter) to be connected to Wagtail and integrated with MailChimp.

2. We want to receive the contact form when people that contact us and the webinar form for people that subscribe for the webinar.

**Comment by popovayoana** [comment]
@alexmorev @Alex-Pavlyuk Sales team reported an issue with the forms which is pretty urgent to fix as it messes up the funnels. Can we look into that?

**Comment by popovayoana** [comment]
@alexmorev @Alex-Pavlyuk also not sure why we have four filters here:
![image](https://user-images.githubusercontent.com/78435662/221867137-a38a6227-3133-4dc1-b3ef-64e18ee64b4b.png)

I think we should just have three: contact, webinar, newsletter. right?

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev hey guys, we now started receiving some submission/subscribe forms. I'm not sure what that is... 

![image](https://user-images.githubusercontent.com/78435662/222409600-1196e488-fcde-45e8-b792-f931f6a48d3c.png)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk hey, any update on this?

**Comment by alexmorev** [comment]
@popovayoana Fixed. Please check and give your feedback.

**Comment by popovayoana** [comment]
@alexmorev it seems the contact inquiries are now fine. however, there's a problem with the contact form itself:

1. the consent message doesn't look good (it's smashed) 
- can we fix spacing
- can we just leave _"I would like to receive email updates, news and events from ckan.org"_?
- can we add a note somewhere that _"Your information will be used in accordance with our Privacy Policy. You may opt-out at any time."_ (compliance purposes)
![image](https://user-images.githubusercontent.com/78435662/224102465-600f77f2-4cff-4a8a-894f-a0dc71ea3a5d.png)

3. after submission, I get a quick thank you message and then it redirects me to this:
![image](https://user-images.githubusercontent.com/78435662/224101169-7b35f95b-86b1-4a78-9ee1-8bbf2797e6f1.png)

4. contact is not added to Wagtail and Mailchimp

**Comment by alexmorev** [comment]
Try to clear your browser cache and reopen the site.
I've just tried this by myself and that is the result
![image](https://user-images.githubusercontent.com/107184558/224164556-47ed2058-7686-475d-ba2e-334f90d95b7d.png)

**Comment by popovayoana** [comment]
@alexmorev hey alex, it worked! thanks! 💌  // cc @Alex-Pavlyuk 

Can we just fix these two things: 
**- [ ] 1. change the consent message** 
  - [ ] leave only "_I would like to sign up to receive emails with the latest news, events, and more from ckan.org._"
  - [ ] add add a note "_Your information will be used in accordance with our Privacy Policy. You may opt-out at any time._ (compliance purposes)

**- [ ] 2. add "Thank you" message after submitting a form** 
The message can either appear as an overlay (modal/pop-up) or replace the contact form content within the same page + it should be styled in line with our website's design and branding). The text for the "Thank You" messages is as follows:
- After users submit the contact form: 
> Success! 🎉 Thank you for reaching out to us. We appreciate your time and effort in completing our contact form. Rest assured, our team is eager to connect with you and will be in touch shortly._
- After users submit the webinar form: 
> Success! 🚀 Thank you for signing up for CKAN Monthly Live! We're happy to have you on board! You've been successfully subscribed to our webinar list, and we'll be sending you an invitation to our next CKAN Monthly Live event very soon. Get ready to dive into the world of CKAN with informative sessions, expert insights, and engaging discussions!

**Comment by alexmorev** [comment]
@popovayoana Done. Now it's being tested on dev server. I've added recaptcha v3 instead of the second version. Hope it'll be available on the main server in 1-2 days. If you have any suggestions or notes please let me know.

**Comment by alexmorev** [comment]
@popovayoana The above mentioned changes are available on the main server.

**Comment by popovayoana** [comment]
@alexmorev great, everything is perfect! i consider this issue FIXED so closing. thanks! 🙏
