### ISSUE TITLE
Add short description about the author 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#14]
**Description**
Blog page >> There is no information about the author of the blog posts. 
![image](https://user-images.githubusercontent.com/78435662/127217998-32f6dac8-dd02-447e-9d66-4d59b9f5221b.png)

**Expected behaviour**
When clicking on the name of the author under the article we want to have a short description about this person (like on the old ckan.org). It might be fetched from GitHub profiles for example. The description could be above/beneath the list of articles by this author - up to the designer.

I imagine something really simple e.g.:
1. name + role (like on [Google Blog](https://blog.google/inside-google/googlers/how-leading-google-one-solving-puzzle))
![image](https://user-images.githubusercontent.com/78435662/127446879-0bc70d99-3fbd-4ae7-9049-c3be6a5882d3.png)

2. picture + name + role + short description
![image](https://user-images.githubusercontent.com/78435662/127219732-aef66744-0797-417b-80aa-c198bfdc0600.png)

**Comment by Alex-Pavlyuk** [comment]
@popovayoana done pls check. Now every Blog creator has a Profile entity in the left sidebar where they can add their personal information (admins and moders can edit it). The information is visible if you click on Author's name on the Blog page (for authors where it was set)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk **there seems to be a missing field for the name of the user...**

![image](https://user-images.githubusercontent.com/78435662/192881888-f14e47b7-adad-433a-8158-0fb88ff80c0a.png)

**also, when trying to create a new profile, it gives me:** 

![image](https://user-images.githubusercontent.com/78435662/192881603-9b53e8ae-2d32-4e42-b886-7d6d2ee6ac99.png)

**Comment by Alex-Pavlyuk** [comment]
Ok, we will fix it soon

**Comment by Alex-Pavlyuk** [comment]
@popovayoana it was fixed pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk When filtering by author, i encounter 2 problems:
1. results show all articles _published by this person (author)_ instead of _written by author_. imo results should show only _written by author_ (see example below)
2. results show all article in chronological order, starting from the oldest to the newest. imo it should be the opposite - from the most recent to the oldest. 

Example
![image](https://user-images.githubusercontent.com/78435662/200862049-3ed2caab-e035-4f38-959c-12f042762888.png)
![image](https://user-images.githubusercontent.com/78435662/200862259-ada5ddce-c8cb-44d6-bf12-5496635e3387.png)

Comment: I didn't write the article, I just published it (the name of the author is pointed in the article). However, it shows up here: https://ckan.org/blog/author/yoana.popova@datopian.com

**Comment by popovayoana** [comment]
@Alex-Pavlyuk also, not super clear on:

1. how do I add authors? currently, I have a dropdown list of users (where did all these folks come from?! :D ) but what if the author is not in this dropdown list?
2. how do I add author's image? now there's an image of a building by default which is not okay, at least some avatar? or fetch it from github? 

![image](https://user-images.githubusercontent.com/78435662/200869049-87a7b41b-5cba-4ae9-ac85-d1d901a59e5a.png)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk just tagging ; ))

**Comment by Alex-Pavlyuk** [comment]
The author's image is the user's image on the site who is an author, at least, it should work so. I will double check it later.
In the dropdown, you can see all site users by username, 
on the form we have additional fields which we can't be easily added to the user profile form directly

**Comment by Alex-Pavlyuk** [comment]
@popovayoana I checked it, and it works as expected. If you still have a problem pls let me know

**Comment by alexmorev** [comment]
@popovayoana Please let me know about this issue. Can we close it?

**Comment by popovayoana** [comment]
@alexmorev closing as FIXED.
