### ISSUE TITLE
Reduce subscription snippets to two

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#15]
- **Description**
We now have 5 types of subscription snippets: 
- [x] speak with us with a pop-up contact form (Home page) **this one is ok**
- [x] speak with us with an email box, no pop-up contact form (Community) **done: changed to a pop-up one**
- [x] subscribe to get new posts (Blog) **done: removed**
- [x] join our next webinar (Home page) **this one is okay**
- [ ] schedule a chat (CKAN for Government) **TODO: change to a pop-up one**
- [ ] schedule a chat (CKAN for Enterprise) **TODO: change to a pop-up one**

**Expected behaviour**
We want to reduce the types of subscription snippets to these two:
- speak with us with a pop-up contact form 
- join our next webinar

**Comment by Engerrs** [comment]
Hi @Alex-Pavlyuk , done in one of tickets. Will be deployed soon to PROD.

**Comment by Alex-Pavlyuk** [comment]
@popovayoana now we have:

- speak with us with a pop-up contact form
- join our next webinar

and the 
Steward Form in the top of /government and /enterprise pages

**Comment by popovayoana** [comment]
@Alex-Pavlyuk perfect, all works great!

**Comment by popovayoana** [comment]
@Alex-Pavlyuk sorry, I am reopening because I did not realize that the steward form in the top of government/enterprise pages is also with an email box. I thought it's with a pop-up like the main one. Not sure if I should open a new issue for this or we can work in this one. Basically, all in all what we want is just two subscription forms on the website: 1) for webinar and 2) speak with us with a pop-up. So the steward forms on government/enterprise pages should be changed to a one with a pop-up. Thanks!

**Comment by popovayoana** [comment]
@Alex-Pavlyuk can we change the steward forms on government/enterprise pages to be like the standard pop-up one? We still receive emails from these form and it makes no sense. Thanks!

**Comment by Alex-Pavlyuk** [comment]
@popovayoana I expect to get help from community to work on issues

**Comment by popovayoana** [comment]
@Alex-Pavlyuk Can we please take some action re these two points:
- [ ] schedule a chat (CKAN for Government) **TODO: change to a pop-up one**
- [ ] schedule a chat (CKAN for Enterprise) **TODO: change to a pop-up one**

We want to get rid of the "schedule a chat" subscription form on government/enterprise pages the way it is now and substitute it with the one with a pop-up contact form. Let me know who should I get in contact with regarding this issue.

**Comment by Alex-Pavlyuk** [comment]
@popovayoana I'll try to prioritise this work

**Comment by popovayoana** [comment]
@Alex-Pavlyuk any updates on that?

**Comment by Alex-Pavlyuk** [comment]
@popovayoana will be fixed next week

**Comment by popovayoana** [comment]
@Alex-Pavlyuk great, thank you, can't wait ; )

**Comment by popovayoana** [comment]
@Alex-Pavlyuk any update on this?

**Comment by Alex-Pavlyuk** [comment]
fixed
