### ISSUE TITLE
A quote is positioned on the wrong place

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#17]
**Description**
On ckan.org/showcase there is a quote that interrupts Government section and shouldn't be there.
![tempsnip](https://user-images.githubusercontent.com/78435662/128602054-f7c15574-cf9f-405f-a488-20826a07a889.png)

**Expected behaviour**
The quote should be at the beginning, at the end or between Government and Enterprise sections.

**Comment by Engerrs** [comment]
Hi @Alex-Pavlyuk , updated quote position. Will be deployed soon to PROD.

**Comment by Alex-Pavlyuk** [comment]
It was deployed. @popovayoana pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk checked, all good, closing
