### ISSUE TITLE
Experiencing a 502 Bad Gateway error 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#183]
## Description
Experiencing a 502 Bad Gateway error when a. attempting to view a newly published article on CKAN's blog and b. when trying to create a new article. However, all other existing articles on the blog are accessible, suggesting that the issue might be localized to the publishing process or to new content specifically.

**Steps to Reproduce**
1. Navigate to the new article URL https://ckan.org/blog/call-to-ui-designers-front-end-developers-ckan
2. Observe a 502 Bad Gateway error
3. Try to create a new article through the CMS
4. Again, observe a 502 Bad Gateway error
5. Browse other existing articles on the CKAN blog
6. Note that these are accessible and render as expected

**Comment by Alex-Pavlyuk** [comment]
@popovayoana solved. Pls check
The problem was in one of the tags. Slashes in tags are unacceptable since tags are used to form URLs for filtering by tags, and slashes break the path. We will add a tooltip about it for the field later.

**Comment by popovayoana** [comment]
> @popovayoana solved. Pls check The problem was in one of the tags. Slashes in tags are unacceptable since tags are used to form URLs for filtering by tags, and slashes break the path. We will add a tooltip about it for the field later.

thank you for your immediate reaction! ❤️ 🙏 
closing as FIXED.

**Comment by alexmorev** [comment]
@popovayoana  I've fixed this issue and now you can use special symbols like "/" in tag names without errors.
