### ISSUE TITLE
Blog post "Published on" date incorrectly updating on edits

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#187]
## Description
There is an issue with the date management on the CKAN Blog where the "published on" date of blog posts is automatically updating to the current date whenever an article is edited. This behavior can lead to confusion, as seen in the case of an article about a UI designer: https://ckan.org/blog/call-to-ui-designers-front-end-developers-ckan. Originally published months ago, a recent edit (today) caused the publication date to display as today's date, potentially misleading readers into thinking the content is new... 

Note: The issue is particularly problematic for posts that are time-sensitive or related to events and announcements. We need to have some clear distinction between 'created date', 'published date', and 'last edited date'. 

### Steps to Reproduce

1. Edit an existing blog post on the CKAN Blog that was published at an earlier date
2. Save the changes and view the post on the blog
3. Notice that the "published on" date reflects the edit date, not the original publication date

### Expected Result
Editing a blog post should not change its original "published on" date. The date should remain as the initial publication date to avoid confusion and maintain the chronological integrity of the blog.

### Actual Result
The "published on" date of a blog post changes to the current date whenever the post is edited, leading to potential misinformation regarding the timeliness of the content.

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev hey guys, can you have a look at this as well?

**Comment by alexmorev** [comment]
@popovayoana Fixed. Please check.

**Comment by popovayoana** [comment]
@alexmorev works perfect, thanks!
