### ISSUE TITLE
Excessive spacing in Wagtail header formatting 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#199]
## Description
There is an issue with the formatting of headers (H1, H2, H3 etc) in Wagtail. There appears to be inconsistent and excessive spacing in two key areas:
1. **Between Headers** - the spacing between different headers (H1, H2, H3 etc) is larger than expected, disrupting the flow and readability of the content
2. **Between Text and Headers** - there is excessive space between the end of a text block and the subsequent header, leading to a disjointed visual presentation

## Expected Behavior
The spacing between headers and between text and headers should be uniform and adhere to standard web content formatting practices. This ensures a cohesive, visually appealing layout that enhances readability.

## How it looks like now
![image](https://github.com/ckan/ckan.org/assets/78435662/16e9526e-a967-4538-9c7b-3daa5ef197cc)
![image](https://github.com/ckan/ckan.org/assets/78435662/38d679ca-569f-45df-8f17-bd95515f197a)

**Comment by popovayoana** [comment]
@alexmorev @Alex-Pavlyuk hey guys! first, happy new year! ; )) may your debug sessions be short, your coffee/tea strong, and your connections with others meaningful! second, can you look into that? : )) thanks!

**Comment by Alex-Pavlyuk** [comment]
@popovayoana we will start to work on it soon

**Comment by Alex-Pavlyuk** [comment]
@popovayoana it is changed now pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk great job so far! just a couple of quick things to tweak:

1. headings size: H3, H4, and H5 look almost the same size right now... H3's a bit different in color and padding, but could we make them more distinct in size?
2. padding: let's match the padding with the heading sizes - it'll look neater that way...

size
![image](https://github.com/ckan/ckan.org/assets/78435662/fa21be99-fb17-4194-afaf-47dcbdda62c6)

padding
![image](https://github.com/ckan/ckan.org/assets/78435662/34f523bb-fe65-415e-be3f-7b2821491e9d)

**Comment by alexmorev** [comment]
@popovayoana It's done. Please check. Waiting for your feedback.

**Comment by popovayoana** [comment]
@alexmorev nothing has changed for me so far... 😕 should I wait a bit? I'm testing with this article: https://ckan.org/admin/pages/376/view_draft/

**Comment by alexmorev** [comment]
@popovayoana Fixed. Please re-check.
![image](https://github.com/ckan/ckan.org/assets/107184558/8eb387f4-7f27-477f-a0df-a063a22dd409)

**Comment by popovayoana** [comment]
@alexmorev the header font size is perfect! we just need to tweak the line height for h4, h5, and h6. not super sure but I'm leaning towards maintaining a consistent **4px difference** between font size and line height across all headers, from h1 to h6 would look good (why 4px? - it's already looking good on h1 and h3, unless I'm mistaken)

here’s a tentative suggestion (but please, apply your expertise to adjust as you see fit):
- for h4, now at Size 28px and Line Height 42px → Let's try Line Height 32px
- for h5, now at Size 24px and Line Height 36px → Let's try Line Height 28px
- for h6, now at Size 20px and Line Height 30px → Let's try Line Height to 24px
 - etc

![image](https://github.com/ckan/ckan.org/assets/78435662/ffee0013-23a0-4077-971e-06477db71b43)

**Comment by popovayoana** [comment]
@alexmorev @Alex-Pavlyuk everything looks good overall, but I've noticed an issue with the font size of hyperlinks in the titles. when inserting a link into the titles, the links appear with a smaller font size compared to the rest of the text. 

here is an image for reference:
![image](https://github.com/ckan/ckan.org/assets/78435662/6bb734ce-a689-479c-9c23-f8a05e26e708)

you can see the problem in the preview link: https://ckan.org/admin/pages/380/edit/preview/?mode=

Additionally, there is one more minor thing: the font size of H6 in the admin panel is too small:
![image](https://github.com/ckan/ckan.org/assets/78435662/1762c311-880e-47f5-b87e-ca9cadc941ab)

**Comment by popovayoana** [comment]
@alexmorev and one more thing... can we adjust the kerning (letter spacing) for all H1 to H6 headings to improve readability? the current kerning in the H1 to H6 headings is too tight, making the text appear cramped and less readable. I am not sure how to give you proper instructions because I don't know the exact current letter spacing, but it looks too tight and needs to be loosened up... wdyt?

![image](https://github.com/ckan/ckan.org/assets/78435662/21ab88b6-b367-4ab1-b21e-cb31205735fb)

**Comment by Alex-Pavlyuk** [comment]
fixed @popovayoana pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk closing as FIXED. works perfect! 🤗
