### ISSUE TITLE
502 Bad Gateway Error on Login at ckan.org

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#200]
## Description
When attempting to log in at CKAN's main site (https://ckan.org > Log in), the server consistently returns a 502 Bad Gateway error. 

### Steps to Reproduce
1. Navigate to https://ckan.org/ and click on 'Log in'
2. Observe the 502 Bad Gateway error upon redirection to https://ckan.org/accounts/login

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev this raises a question about the necessity of this login feature - it's only for admins, isn't it? I always use https://ckan.org/admin/pages/7 for admin access. But, having that other login might be misleading for our regular users, and I've been getting quite a few questions about it. Should we think about tweaking this to avoid any mix-up?

**Comment by Alex-Pavlyuk** [comment]
@popovayoana We planned to use the front-end link to give ability to blog authors to enter the site easily
when I logged I see: 
![image](https://github.com/ckan/ckan.org/assets/15265061/b66d1ad1-2cc6-4208-a786-a1577d87a2bb)
there are not 502 errors for me.
How do we reproduce it?

**Comment by Alex-Pavlyuk** [comment]
another related issue that can cause 502 error is fixed, pls check it again

**Comment by popovayoana** [comment]
@Alex-Pavlyuk all works now! thanks.
closing as FIXED.
