### ISSUE TITLE
Bug: Search functionality issues on CKAN.org blog

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#207]
## Description
The search functionality on the CKAN.org blog is not operating as expected. Queries are either returning no results or incomplete results, even though relevant articles are present on the blog.

### Examples of the Issue:

**Query: "POSE"**
- Expected result: At least three articles related to the POSE project
- Actual result: No results are found
- Reference link: https://ckan.org/blog/search?query=POSE

**Query: "digital"**
- Expected result: An article "CKAN is now a Digital Public Good"
- Actual result: Only one result pertaining to the civic data lab, omitting other relevant articles
- Reference link: https://ckan.org/blog/search?query=digital

**Query: "Digital Public Good"**
- Expected: The article titled "CKAN is now a Digital Public Good"
- Actual result: Only one unrelated result about civic data lab
- Reference: https://ckan.org/blog/search?query=Digital+Public+Good

## Screenshots
POSE
![image](https://github.com/ckan/ckan.org/assets/78435662/6cab5e89-3a14-4bce-83f5-61844e6c4ddc)

digital
![image](https://github.com/ckan/ckan.org/assets/78435662/68374860-84b8-4563-9324-85cc07eecedb)

DPG
![image](https://github.com/ckan/ckan.org/assets/78435662/44dad701-da60-4b26-ae18-8677e325b089)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev hey guys, we've got some glitches with the blog's search function on the website - it isn't pulling up the articles we know are there. can you have a look?

**Comment by Alex-Pavlyuk** [comment]
@popovayoana ok we will check

**Comment by alexmorev** [comment]
@popovayoana Fixed. Please check.
Take into account that you can see only "live" (published) articles in search results.

**Comment by Alex-Pavlyuk** [comment]
fixed @popovayoana pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk works great, thanks! closing as FIXED.
