### ISSUE TITLE
[Bug] Blockquote display issue: Text invisible except for hyperlink colors 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#215]
## Description
When using blockquote in Wagtail, there appears to be a styling issue where the text within the blockquote becomes invisible (white text on a presumably white background) except for hyperlinks, which are displayed in red. 

## Steps to Reproduce
1. Create a new page in Blog in the Wagtail editor
2. Navigate to body text where blockquotes are utilized
3. Insert a blockquote containing both regular text and hyperlinks
4. Preview or publish the page
5. See that the blockquote text is invisible except for the red hyperlinks

## Expected Behavior
The text within blockquotes should be:
1. clearly visible against the background
2. with distinct styling that differentiates it from the rest of the page content. What I mean by "distinct styling" is:

> - **Left Border Line**
>   - Color: Red or Grey (choose in accordance with the website's design theme)
>   - Thickness: Suitable to be noticeable but not overpowering (e.g., 2-4px)
> - **Indentation**
>   - The blockquote should start ~2 cm to the right of the main content's alignment indent block quotes should be 0.5 inches from the left (this is acc to APA and MLA styles)
> - **Text Style**
>   - Font: Maintain the same font as the body text for consistency
>   - Text Size: Set at 18px to subtly stand out against the body text, which is smaller by 2px
>   - Weight: Normal (the current default bold styling should be removed)
>   - Italics: Not applied by default. Admins should have the option to italicize text as desired
> - **Background of blockquote**
>   - Maintain the current background color; no change is required (the blockquote should seamlessly integrate with the page without a distinct background color, relying solely on the red/grey left border line for distinction)

## Screenshots
![image](https://github.com/ckan/ckan.org/assets/78435662/ac5a275c-4b96-48d0-8e8b-50fbdbaddf98)

![image](https://github.com/ckan/ckan.org/assets/78435662/0192623b-7d65-4048-a8ed-997383d1338d)

![image](https://github.com/ckan/ckan.org/assets/78435662/f1b9e02a-c6e6-4769-9c80-36dace653005)

## Examples of how it should look like (ignore background)

![image](https://github.com/ckan/ckan.org/assets/78435662/c9363fe0-739d-457d-a4f2-7426d155608f)

![image](https://github.com/ckan/ckan.org/assets/78435662/2773780a-83f7-4c63-9b25-0df8205e2d4c)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev hey guys, can you look into this? if we can at least fix the bug soon, that'd be great... thanks!

**Comment by Alex-Pavlyuk** [comment]
> @Alex-Pavlyuk @alexmorev hey guys, can you look into this? if we can at least fix the bug soon, that'd be great... thanks!

we will fix it soon

**Comment by alexmorev** [comment]
@popovayoana It has been fixed. Please review.

**Comment by popovayoana** [comment]
@alexmorev it works perfect now, the only thing is the font size of the hyperlink is smaller compared to the rest of the text

![image](https://github.com/ckan/ckan.org/assets/78435662/ae09a217-58c6-4768-9d0b-f9839b6449fe)

**Comment by Alex-Pavlyuk** [comment]
fixed @popovayoana pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk works perfectly! FIXED.
