### ISSUE TITLE
Missing confirmation message after CKAN contact form submission

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#220]
## Description
Users are redirected to the homepage without any confirmation after submitting the contact form on ckan.org. Previously, a popup or similar notification confirmed the submission. This absence confuses users about whether their message was sent successfully.

## Expected Behavior

- **Option A:**
  - Display a clear, explicit message confirming successful submission immediately after the form is submitted
  - After showing the confirmation message, redirect the user to the homepage
- **Option B:**
  - Redirect users to a dedicated "thank you for contacting us" page immediately after form submission

If we go with option B:

## How the redirect page should look like
In terms of design, it should be similar to https://ckan.org/newsletter/subscription.

Copy: 

> h1 Thank you for contacting us!
> 
> h2 What happens next
> Thank you for reaching out! We value your interest and are ready to help. Our team will review your inquiry and respond within 48 hours.
> 
> h2 In the meantime
> 📝 **[Explore Our Blog](https://www.ckan.org/blog)**: Dive into our blog for comprehensive articles and insights that reflect our expertise and passion for our field.
> 
> h2 Join our community
> **🔗 [Follow us on LinkedIn](https://www.linkedin.com/company/ckanproject)**
> Join our professional network for deeper insights and updates.
> **🐦 [Follow us on X](https://www.twitter.com/ckanproject) (formerly Twitter)**
> Stay up-to-date with the latest news and quick updates.
> **✉️ [Subscribe for direct updates](https://ckan.org/newsletter/subscription/)**
> Get the latest news and exclusive content straight to your inbox.

**Comment by popovayoana** [comment]
@agmorev @Alex-Pavlyuk can you have a look at this?

**Comment by Alex-Pavlyuk** [comment]
yes it is a valid issue that must be fixed, we will work on it

**Comment by Alex-Pavlyuk** [comment]
@popovayoana pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk it works! FIXED.

![image](https://github.com/user-attachments/assets/3560a9ca-9be2-423c-b043-8644d989afbd)
