### ISSUE TITLE
update community personal info

### ISSUE THREAD

**Issue by wardi** [ckan/ckan.org#221]
Please update my info on https://ckan.org/community :

<dl><dt>description</dt><dd>CKAN Team lead / Senior Solutions Architect at Link Digital</dd>
<dt>twitter</dt><dd>https://twitter.com/wardi_</dd>
<dt>linkedin</dt><dd>https://www.linkedin.com/in/ianward/</dd>
</dl>

**Comment by Alex-Pavlyuk** [comment]
@wardi done
