### ISSUE TITLE
Blog posts are ordered by modification date, not creation date in index page

### ISSUE THREAD

**Issue by amercader** [ckan/ckan.org#225]
I edited an old 2021 page and now it's coming up at the top of https://ckan.org/blog

![Screenshot 2024-07-24 at 15-50-48 CKAN Blog](https://github.com/user-attachments/assets/b7a818df-ce66-4d24-8f7b-d9174c0cbbb5)

**Comment by alexmorev** [comment]
@amercader It's fixed. Please check

**Comment by amercader** [comment]
@alexmorev The last modified posts are still coming up first I'm afraid. I edited the "Investment to Strengthen..." one from last June and it now comes up on top:

![Screenshot 2024-08-28 at 13-32-05 CKAN Blog](https://github.com/user-attachments/assets/fbdc9c38-d7fd-4b4e-875b-10d9308517c5)

**Comment by amercader** [comment]
@alexmorev it's weird, I tested in different browsers, the first time the page loads the posts are ordered incorrectly. Once I hard refresh, the page the order is fixed.

**Comment by Alex-Pavlyuk** [comment]
@amercader could you pls check how it looks now

**Comment by amercader** [comment]
All looks good, thanks
