### ISSUE TITLE
Add CTA "Star us on Github" 

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#24]
**Description**
We might want to consider having a call to action "Star us on Github" somewhere on the website. Not sure about the proper position. My suggestions would be:
1. We either change "View on Github" with "Star us on Github" or 
2. We put it somewhere at the bottom e.g. next to the social media icons

**Expected behaviour**
![image](https://user-images.githubusercontent.com/78435662/133392325-3eec483d-fa8e-47a1-ae61-35d25489b51a.png)

**Comment by Alex-Pavlyuk** [comment]
@popovayoana Is it really an important feature for now?

**Comment by Alex-Pavlyuk** [comment]
@popovayoana the best that we can do for that ticket is done - see right bottom corner. But we didn't find a way how to set Stars automatically after one click.

**Comment by popovayoana** [comment]
FIXED.
