### ISSUE TITLE
Search on CKAN.org doesn't return relevant results

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#248]
## Description
The search functionality on CKAN.org is currently not working as expected. Regardless of the query entered, the results returned are irrelevant and appear to be the same for all searches. 

Steps to Reproduce:

1. Go to https://ckan.org
2. Use the search bar to enter any query e.g.
  - https://ckan.org/blog/search?query=open+data
  - https://ckan.org/blog/search?query=Digital+Public+Good
  - https://ckan.org/blog/search?query=POSE
3. All queries return the same irrelevant results.

## Screenshots 

![image](https://github.com/user-attachments/assets/f4e3fbed-bf06-413d-b91e-d77b04707962)
![image](https://github.com/user-attachments/assets/a409f5d1-83b9-4c14-a940-bdcacfcf99cd)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @agmorev could you have a look?

**Comment by Alex-Pavlyuk** [comment]
@popovayoana It was an issue with the cache system, but now it works as expected.
