### ISSUE TITLE
Missing Sarawak Data Portal In CKAN Showcase Page

### ISSUE THREAD

**Issue by jerrychong25** [ckan/ckan.org#249]
## CKAN version
N/A

## Describe the bug
Hi CKAN Team,

Good day.

I'm Jerry Chong based in Kuala Lumpur, Malaysia.

For CKAN Showcase page, it's missing Sarawak Data Portal (https://data.sarawak.gov.my/home/home/index/).

Sarawak Data is using CKAN platform as per highlighted in https://data.sarawak.gov.my/home/article/view/22.

Could assist to add this website into CKAN Showcase page?

Thank you.

Best Regards,
Jerry Chong

### Steps to reproduce
1. Visit https://ckan.org/showcase
2. There is no Sarawak Data highlighted in the same page.

### Expected behavior
Sarawak Data should showcase in https://ckan.org/showcase

### Additional details
N/A

**Comment by wardi** [comment]
Hello @popovayoana is this the right place for this issue?

**Comment by Alex-Pavlyuk** [comment]
Hello @jerrychong25 the showcase page does not show all CKAN portals, just some examples. The full list you can find for example here: https://datashades.info/

**Comment by jerrychong25** [comment]
> Hello @jerrychong25 the showcase page does not show all CKAN portals, just some examples. The full list you can find for example here: https://datashades.info/

Hi @Alex-Pavlyuk ,

Noted on this.

Here is DataShade Info for data.sarawak.gov.my:
- https://datashades.info/portal/https%3A%2F%2Fdata.sarawak.gov.my%2Fhome%2Fhome%2Findex%2F

Thanks!
