### ISSUE TITLE
Add a calendar to Events page

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#25]
**Description**
We want to have a calendar on Events page so that dates for events (CKAN Monthly Live, CKAN tech meetups, and hopefully more) can be listed publicly - with a little info about each event.

**Expected behaviour**
When landing on Events page one should be able to easily comprehend: types of events we're having, dates, event details. 

**Details**
I imagine it something similar to the pictures below. A normal calendar widget with certain dates highlighted. When clicking on the highlihted date, the user sees more details about the event. The mechanism could be different, this is just one option. 

For a beginning, an easier thing we could prob do is just to find a way list regular events on Events page
- CKAN Monthly Live - every third Wednesday of the month at 1 PM UTC (+meeting details)
- CKAN Tech meetings - every Tuesday and Thursday at 1 PM UTC (+meeting details)

![image](https://user-images.githubusercontent.com/78435662/133398239-f7213c76-22a5-411d-b60d-8d1828e07729.png)

![image](https://user-images.githubusercontent.com/78435662/133398423-e7bc8b88-b3b1-4b2a-bc3d-d6988e39db61.png)

**Comment by Alex-Pavlyuk** [comment]
before someone will start work on this, we need to prepare a design mockup to follow current styles
this task requires more clarifications on how it should work, a list of popups or actions that will help users to find events.

**Comment by Alex-Pavlyuk** [comment]
Most likely it will be discussed here: https://github.com/ckan/ckan.org/issues/31

**Comment by popovayoana** [comment]
@Alex-Pavlyuk noted!

**Comment by Alex-Pavlyuk** [comment]
I'm closing this ticket to avoid double discussions
