### ISSUE TITLE
Too much spam from Contact form

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#4]
**Describe the problem**
Our contact form is notorious for collecting spam from bots. Most of the messages that come are spam. 

**Suggestion**
Adding Google Recaptcha (wagtail-django-recaptcha package) or something to the contact form to reduce the number of fake form submissions.

**Comment by Alex-Pavlyuk** [comment]
As I see it is not automated spam. We use hidden recapthca already for all our forms, but it will not help against humans.
If anyone has suggestions on how to reduce the span pls let us know here.

**Comment by popovayoana** [comment]
@Alex-Pavlyuk I bet u've been testing something... FLOODED for 15 mins :D T https://vimeo.com/574466828

**Comment by Alex-Pavlyuk** [comment]
Yes I see. It is definitely flood. We will think how to avoid it.

**Comment by Alex-Pavlyuk** [comment]
@popovayoana The fix was deployed. Pls confirm that it helps

**Comment by monikappv** [comment]
@Alex-Pavlyuk we haven't received any form submissions in the last 22 hours, so I assume it works. Also, just out of curiosity, could you please share what approach you've used?

**Comment by Alex-Pavlyuk** [comment]
It was just another reCaptcha. I'm glad that the issue was fixed. :)
