### ISSUE TITLE
Pagination broken on blog page

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#40]
**Description**
All pages on the blog page are linked to page 1. When clicking on page 2 and the domain shows https://ckan.org/blog?page=2 or page 3 (https://ckan.org/blog?page=3), it directs you to page 1. Browsers the bug is found in: Chrome, Mozilla, Internet Explorer.

**Expected behaviour**
Pagination should work properly so that each page corresponds to the content.

**Comment by popovayoana** [comment]
@Alex-Pavlyuk can we fix this relatively soon?

**Comment by Alex-Pavlyuk** [comment]
We will try to fix soon

**Comment by Alex-Pavlyuk** [comment]
@popovayoana could you pls check it now, must work well

**Comment by popovayoana** [comment]
@Alex-Pavlyuk works well, closing as FIXED.
