### ISSUE TITLE
Steward form leftover bug

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#41]
**Description**
This is connected to issue #15 which was FIXED. For more context, please see issue #15. In brief, we reduced the steward forms to only one with a pop-up contact form (where users fill out details about their reasons of contact). The problem is we still receive some steward form subscriptions without any other information in our inboxes which doesn't make sense.

**See images below** 
![image](https://user-images.githubusercontent.com/78435662/160615942-481c53f8-f657-4057-a079-54f878919bbd.png)

![image](https://user-images.githubusercontent.com/78435662/160617474-8608a85d-3068-4a68-8699-8275fd195148.png)

**Expected behaviour**
We want to receive only forms that come along with the submitted contact form:

![image](https://user-images.githubusercontent.com/78435662/160617847-6b08d6ee-ada3-42cd-9fd2-33f0dab1c7e9.png)

**Comment by Alex-Pavlyuk** [comment]
fixes @popovayoana pls check

**Comment by popovayoana** [comment]
[update] so far haven't received the leftover forms, I think we consider that FIXED. thanks @Alex-Pavlyuk
