### ISSUE TITLE
Update community page

### ISSUE THREAD

**Issue by wardi** [ckan/ckan.org#45]
Please update my job title on the Community page to "Developer at Government of Canada"

I don't think anyone cares which department I'm working for, and that department changed a few years back anyway :-)

**Comment by popovayoana** [comment]
@Alex-Pavlyuk tried but don't have the necessary permissions. it's a pretty quick fix, can we fix it? // @wardi

**Comment by wardi** [comment]
@popovayoana I assume it's part of a CMS because I don't see it in the source. I don't have access to the CMS to make any changes myself.

**Comment by Alex-Pavlyuk** [comment]
@wardi @popovayoana changed.

**Comment by Alex-Pavlyuk** [comment]
@popovayoana I have fixed the role permission table, now all Moderators can add/edit snippets

**Comment by wardi** [comment]
Hey, you removed my "CKAN tech lead" title :-( Oh, well I guess it didn't give me any real power anyway.

**Comment by Alex-Pavlyuk** [comment]
@wardi No worries I'll fix that
