### ISSUE TITLE
Update link to LinkedIn account on website

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#48]
**Description**
We have created a brand new company page on LinkedIn. We want the social media links on the footer of the website to be updated. The current link to LinkedIn redirects to CKAN Association LinkedIn Group - https://www.linkedin.com/groups/6795833. We want to add link to CKAN LinkedIn Company Page: https://www.linkedin.com/company/80804045. 

I guess we can either have two LinkedIn icons - one pointing to group and another to company page or just one that leads to the company page.

![image](https://user-images.githubusercontent.com/78435662/172001352-1b28e4d6-57b3-4fff-bb8f-1e8656dcfce9.png)

**Comment by alexmorev** [comment]
The link have been already changed

**Comment by Alex-Pavlyuk** [comment]
the change will be deployed soon together with other changes

**Comment by Alex-Pavlyuk** [comment]
deployed
