### ISSUE TITLE
Monthly live posts have confusing slug

### ISSUE THREAD

**Issue by wardi** [ckan/ckan.org#49]
E.g. https://ckan.org/events/ckan-monthly-live-june-11 looks like a meeting that happens on "June 11". Can we remove the month name from the slugs for these posts?

**Comment by Alex-Pavlyuk** [comment]
I think it is to highlight the exact date

**Comment by wardi** [comment]
That's what I mean. "Monthly Live 11" is happening on June 15, but the way the URL looks when you share it makes me think it's on June 11.

**Comment by popovayoana** [comment]
@wardi haven't paid attention to that but you're right - it can be confusing. will change the slugs starting from the next one... // cc @Alex-Pavlyuk
