### ISSUE TITLE
Some elements don't adapt nicely to different viewports

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#5]
**Describe the problem**
1. email box (id = "blogform") generally adapts nicely to different viewports but doesn't adapt nicely to iPad viewport (1024x768) - email box is too close to the text
![image](https://user-images.githubusercontent.com/78435662/125357953-fe773680-e370-11eb-8814-f5df4c1fa7e0.png)

2. email box not justified with text (kind of tries to escape to the right) - Iphone (640x960)
![image](https://user-images.githubusercontent.com/78435662/125360537-b1955f00-e374-11eb-80aa-9fec21ea1ccf.png)

3. social network icons too close to text (Iphone, 640x960)
![image](https://user-images.githubusercontent.com/78435662/125361505-1309fd80-e376-11eb-9830-78afd7d0c167.png)

**Expected behaviour**
1. email box to adapt nicely
![image](https://user-images.githubusercontent.com/78435662/125361912-b22ef500-e376-11eb-9455-b9479850b172.png)

![image](https://user-images.githubusercontent.com/78435662/125361980-ce329680-e376-11eb-964a-a0f86fa200b2.png)

2. aligned with text like this:
![image](https://user-images.githubusercontent.com/78435662/125360899-37190f00-e375-11eb-84cb-3bfe994bc3c6.png)
3. enough spacing between text and icon

**Comment by Engerrs** [comment]
Hi @Alex-Pavlyuk , because of hided/removed the old version of "Subscribe to get new post", this item is not relevant anymore. Will be deployed soon to PROD.
