### ISSUE TITLE
Add past Tech Team members to the community page

### ISSUE THREAD

**Issue by amercader** [ckan/ckan.org#50]
Sorry, I meant to raise an issue about that but forgot. I'd be nice to show past Teach Team members that have moved on to other projects. Right now these would be David Read (https://github.com/davidread) and Tyler Kennedy (https://github.com/tktech), we don't need to show any current affiliation. 
In terms of design and presentation, you can do whatever works best with the current template/models.

**Comment by Alex-Pavlyuk** [comment]
Do we have their real photos somewhere?

**Comment by Alex-Pavlyuk** [comment]
@amercader Ah, ok, then we think where it will be better to place their blocks

**Comment by Alex-Pavlyuk** [comment]
@amercader We added this extra page and the ability to set a developer as former from the Software Engineers snippets, pls give us your feedback
![image](https://user-images.githubusercontent.com/15265061/178421434-7b5eca00-4f6f-438c-b63b-0106c48a623c.png)

**Comment by amercader** [comment]
This looks great @Alex-Pavlyuk !
The only thing I would suggest is to remove the job titles of past members, as these are outdated, and maybe add a link to go back to the community page from the past members page

**Comment by Alex-Pavlyuk** [comment]
@amercader done, pls check now

**Comment by amercader** [comment]
Looks great @Alex-Pavlyuk , thanks
