### ISSUE TITLE
Add a syntax highlighter to the CMS editor

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#87]
**Description**  
When publishing a tutorial/guideline/how-to article, we obviously want it to be user-friendly and properly formatted so that it is easy to use and read. We want to have a syntax highlighting feature.

**Suggestion**
Install a wagtail plugin like https://github.com/FlipperPA/wagtailcodeblock

**Comment by popovayoana** [comment]
@Alex-Pavlyuk can we have this relatively soon?

**Comment by Alex-Pavlyuk** [comment]
Hi @popovayoana ok we'll try to prioritize the work

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev fantastic, you rock! thanks a lot!

**Comment by Alex-Pavlyuk** [comment]
ready. check here: https://ckan.org/blog/migrating-ckan-28-to-ckan-29

**Comment by popovayoana** [comment]
@Alex-Pavlyuk great, looks good! can we have it in black though? i think it looks better, wdyt?

**Comment by Alex-Pavlyuk** [comment]
@popovayoana, it requires changing the library styles, which can affect the ability to update the library in the future. I prefer to leave it as it is now.

**Comment by popovayoana** [comment]
@Alex-Pavlyuk ok, let's consider it FIXED then...
