### ISSUE TITLE
Add Mailchimp integration

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#88]
**Description of the problem**
Atm there's no integration between our webinar/contact forms and the email tools we use. Everything happens manually. We want to automate the process.

**Expected behaviour**
When someone submits a webinar/contact form, we want them to automatically be subscribed to the relative Mailchimp email list. 

**Suggestion for solution**
Mailchimp Integration Feature: https://docs.coderedcorp.com/wagtail-crx/features/mailchimp.html

**Comment by popovayoana** [comment]
@Alex-Pavlyuk who can help with that, it's pretty urgent... current process is painful

**Comment by Alex-Pavlyuk** [comment]
@popovayoana right now we can't start work on this task, but I will try to prioritize it

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev how's this going? can we have this for Christmas? :D It will be the best Christmas gift! : )))

**Comment by Alex-Pavlyuk** [comment]
its in testing now, it will be deployed next week

**Comment by alexmorev** [comment]
@popovayoana , @Alex-Pavlyuk Done. Mailchimp integration was added. Please check, test and give your feedback

**Comment by popovayoana** [comment]
@alexmorev Can you explain how it works? How do I connect the entries from the webinar to the Mailchimp list? // cc @Alex-Pavlyuk

**Comment by alexmorev** [comment]
@popovayoana , @Alex-Pavlyuk To check the functionality of the changes, you need to: 
1. Create a MailChimp account. 
2. Create an audience/list in it. 
![Screenshot from 2023-01-17 14-37-14](https://user-images.githubusercontent.com/107184558/212902858-a2b27714-ece7-459e-8794-c47f21b42268.png)
3. Create additional fields (FORM, COMPANY) in the audience/list inside MailChimp. (use menu "Audience" -> "All contacts" -> "Settings" -> "Audience fields and *|MERGE|* tags")
![Screenshot from 2023-01-17 14-42-53](https://user-images.githubusercontent.com/107184558/212902988-3218a258-ca01-49cc-99f9-2dca724dd27e.png)
4. Save the API key from the MailChimp account and the audience ID in the appropriate form of the site's admin menu "MailChimp settings". (https://ckan.org/admin/settings/contact/mailchimpsettings/2/) 
![Screenshot from 2023-01-05 21-02-04](https://user-images.githubusercontent.com/107184558/212903216-058e153d-ff81-4327-9a74-77e29d079203.png)
5. Fill out the contact/webinar form on the website and send it. 
6. Based on the result, the form will be sent to the appropriate managers mailboxes, and the information about the contact person will be saved in the MailChimp list. 
7. Later, using the Mailchimp toolkit, segments are created in the list by the appropriate fields (in our case, it is logical to use the FORM field) to work with specific groups of contacts.

**Comment by popovayoana** [comment]
@alexmorev @Alex-Pavlyuk can't access https://ckan.org/admin/settings/contact/mailchimpsettings/2/
![image](https://user-images.githubusercontent.com/78435662/214931039-39a3d644-9450-4ce6-8928-72776b5d9eb9.png)

**Comment by alexmorev** [comment]
@popovayoana I've set appropriate access permission. Please try again.

**Comment by popovayoana** [comment]
@alexmorev tested, works great! that's a big game-changer for us! many, many, many thanks! u rock! 🥰 

the only problem is that our CKAN Monthly Live welcome email lands in spam... this is the 1st email one receives after they've subscribed for the webinar. any ideas on how to fix this? or maybe we should just add one sentence to the pop-up message that they should check their spam folder? WDYT?

![image](https://user-images.githubusercontent.com/78435662/216176641-022ab944-ca36-4a8c-b0c0-c6690fe13f7a.png)

**Comment by Alex-Pavlyuk** [comment]
@popovayoana I will check it.

**Comment by alexmorev** [comment]
@popovayoana Please let me know whether Mailchimp is working well and we can close this issue.

**Comment by popovayoana** [comment]
FIXED.
Thanks, @alexmorev 🙏
