### ISSUE TITLE
Add a new pop-up form to "Join our next webinar"

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#89]
**Describe the problem**
Atm if someone wants to subscribe to a webinar, the only thing they have to do is drop their email in the email box. The problem with this is that **a.** we're not collecting enough information (e.g. subscribed/unsubscribed for future events, interests, etc) and **b.** we're collecting a lot of spam. 

## Acceptance criteria
- [ ] the form is implemented on website
- [ ] user receives a thank you message on screen after submission 
- [ ] the webinar submission is added to https://ckan.org/admin/contact/email
- [ ] the form is integrated with Mailchimp

## Analysis
**Suggestion**
1. Add a new pop-up form, similar to the "schedule a call" one (see form suggestion below)
2. Add additional Recaptcha

**Current flow:**

insert email
![image](https://user-images.githubusercontent.com/78435662/193262868-868ca4fd-303e-40a6-8941-e56ad9bfe555.png)

 once inserted - thank you message
![image](https://user-images.githubusercontent.com/78435662/193263565-d43f42dd-fc45-4e6d-b87b-d6c8cb65e3a4.png)

## How we want the pop-up form to look like:

![image](https://user-images.githubusercontent.com/78435662/193460015-72ec84cb-db21-481e-9367-d3968ed6920f.png)
![image](https://user-images.githubusercontent.com/78435662/193460069-0a96c2ca-c4a3-4e94-8f9a-35e8bca158cf.png)

marketing permission alternative of the checkboxes (in this case question should not be required)

![image](https://user-images.githubusercontent.com/78435662/193462719-e56432b1-b6ca-4ee2-a09e-cea61e2f310a.png)

Text:
> 1. **Title:** CKAN Monthly Live
> 2. **Subtitle:** I would like to be invited to the next CKAN Monthly Live meetup. Note: Any information you provide will only be used for inviting you to the CKAN meetups (and, if you opt-in, letting you know about CKAN news and updates). It will not be shared with any third parties.
> 3. **Your Email*** _(required)_
> 4. **Your Name*** _(required)_
> 5. **Your Company/Organization*** _(required)_
> 6. **Are you interested in the technical or non-technical aspects of CKAN?** _(not required)_ | checkboxes: - technical/non-technical/both
> 7. **Would you like to suggest a topic for one of our future meetups?** _(not required)_
> 8. **Would you like to present on CKAN Monthly Live? What topic would you like to talk about?** _(not required)_
> 9. **Any comments or something you'd like to share?** _(not required)_
> 10. **Marketing Permissions**
> 10.1 **Would you like to automatically be invited to future meetups on CKAN Monthly Live? They happen every third Wednesday of the month at 1 pm UTC.*** _(required)_ | checkboxes: yes/no (or just a tick like the one in the contact form)
> 10.2 **Would you like to be informed about other CKAN news and updates?*** _(required)_  | checkboxes: yes/no (or just a tick like the one in the contact form)
> 11. **SUBMIT**
> 12. **Thank you message after submission:** Thank you for your interest in CKAN Monthly Live! You should receive an email with more information shortly.

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev let me know if we can add a pop-up form for the webinars

**Comment by popovayoana** [comment]
@Alex-Pavlyuk @alexmorev any progress on that?

**Comment by Alex-Pavlyuk** [comment]
It is postponed for now

**Comment by alexmorev** [comment]
@popovayoana Done. Please check and give your feedback.

**Comment by popovayoana** [comment]
@alexmorev just received a report related to the form, could you please have a look at https://github.com/ckan/ckan.org/issues/130? thanks!

**Comment by popovayoana** [comment]
@alexmorev can we also get back the thank you message on screen once the user submits the form? currently, it redirects to ckan.org and no thank you message is seen on screen.

**Comment by alexmorev** [comment]
@popovayoana Fixed. Please check and give your feed back.
NOTE. I've removed the mentioned fields from the webinar form however it's still need to be scrolled. So if it's still not what you want please give me your vision.

**Comment by popovayoana** [comment]
hey @alexmorev thanks for fixing this! there's a problem with the text for the checkboxes, can we have it separate and say:

- [ ]  I would like to be automatically invited to future meetups on CKAN Monthly Live.
- [ ]  I would like to subscribe to CKAN Monthly Newsletter and be informed about CKAN news and updates.

![image](https://user-images.githubusercontent.com/78435662/224100039-6967964d-e023-448b-a251-64b76bfcf9c5.png)

**testing report**
1. after submission, I get a quick thank you message and then it redirects me to this:
![image](https://user-images.githubusercontent.com/78435662/224101169-7b35f95b-86b1-4a78-9ee1-8bbf2797e6f1.png)

2. contact is not added to Wagtail and Mailchimp

**Comment by alexmorev** [comment]
Please try to clear cache in your browser and then reopen the site

**Comment by popovayoana** [comment]
@alexmorev thanks, it is FIXED. works perfect.
