### ISSUE TITLE
Fonts size of hyperlinked text is different from plain text

### ISSUE THREAD

**Issue by popovayoana** [ckan/ckan.org#9]
**Describe the bug**
Hyperlinked text fails to resize to 16px on several resolutions (I'm guessing above _max-width: 1024px_, under 1024px is okay) and thus is not in sync with the rest of the text.

**Tested on several resolutions, all above 1024px width look the same:**
- Netbook (1280x800)
![image](https://user-images.githubusercontent.com/78435662/125869886-ae59766e-ba22-44e8-ad1c-fc6d458084d6.png)

**Expected behaviour**
All text should be the same size regardless of the resolution: 
![image](https://user-images.githubusercontent.com/78435662/125870021-ece5eb71-ef5e-48c7-9fb5-733bc0703b24.png)

**Comment by Engerrs** [comment]
Hi @Alex-Pavlyuk , updated font-size of hyperlinks. Will be deployed soon to PROD.

**Comment by Alex-Pavlyuk** [comment]
fixed and deployed @popovayoana pls check

**Comment by popovayoana** [comment]
@Alex-Pavlyuk yes, perfect!
